version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "org.spockframework:spock-core"    # upgrade includes multiple transitive version, not supported
      - dependency-name: "org.spockframework:spock-junit4"  # upgrade includes multiple transitive version, not supported
      - dependency-name: "org.jenkins-ci.jpi"               # maintenance version should not be upgraded automatically
      - dependency-name: "org.openapi.generator"            # API generator depends on the ecu.test openapi.yml
    open-pull-requests-limit: 1
    reviewers:
      - 'ErikRehmTT'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: "10:20"
